package com.sciencelk.dataaccess.entities;
// Generated Jul 13, 2015 9:30:45 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArticleHasTagId generated by hbm2java
 */
@Embeddable
public class ArticleHasTagId  implements java.io.Serializable {


     private int articleId;
     private int tagId;

    public ArticleHasTagId() {
    }

    public ArticleHasTagId(int articleId, int tagId) {
       this.articleId = articleId;
       this.tagId = tagId;
    }
   


    @Column(name="ARTICLE_ID", nullable=false)
    public int getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }


    @Column(name="TAG_ID", nullable=false)
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArticleHasTagId) ) return false;
		 ArticleHasTagId castOther = ( ArticleHasTagId ) other; 
         
		 return (this.getArticleId()==castOther.getArticleId())
 && (this.getTagId()==castOther.getTagId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getArticleId();
         result = 37 * result + this.getTagId();
         return result;
   }   


}


