package com.sciencelk.dataaccess.entities;
// Generated Jul 13, 2015 9:30:45 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name="privilege"
)
public class Privilege  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Set<User> users = new HashSet<User>(0);

    public Privilege() {
    }

	
    public Privilege(String type) {
        this.type = type;
    }
    public Privilege(String type, Set<User> users) {
       this.type = type;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="TYPE", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="privilege")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


