package com.sciencelk.dataaccess.entities;
// Generated Jul 13, 2015 9:30:45 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="\'user\'"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private Privilege privilege;
     private String name;
     private String password;
     private Date lastlogin;
     private boolean locked;
     private int points;
     private Set<Article> articlesForAuthor = new HashSet<Article>(0);
     private Set<Article> articlesForModerator = new HashSet<Article>(0);

    public User() {
    }

	
    public User(Privilege privilege, String name, String password, Date lastlogin, boolean locked, int points) {
        this.privilege = privilege;
        this.name = name;
        this.password = password;
        this.lastlogin = lastlogin;
        this.locked = locked;
        this.points = points;
    }
    public User(Privilege privilege, String name, String password, Date lastlogin, boolean locked, int points, Set<Article> articlesForAuthor, Set<Article> articlesForModerator) {
       this.privilege = privilege;
       this.name = name;
       this.password = password;
       this.lastlogin = lastlogin;
       this.locked = locked;
       this.points = points;
       this.articlesForAuthor = articlesForAuthor;
       this.articlesForModerator = articlesForModerator;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PREVILAGE", nullable=false)
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }

    
    @Column(name="NAME", nullable=false, length=256)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="PASSWORD", nullable=false, length=256)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTLOGIN", nullable=false, length=19)
    public Date getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }

    
    @Column(name="LOCKED", nullable=false)
    public boolean isLocked() {
        return this.locked;
    }
    
    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    
    @Column(name="POINTS", nullable=false)
    public int getPoints() {
        return this.points;
    }
    
    public void setPoints(int points) {
        this.points = points;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByAuthor")
    public Set<Article> getArticlesForAuthor() {
        return this.articlesForAuthor;
    }
    
    public void setArticlesForAuthor(Set<Article> articlesForAuthor) {
        this.articlesForAuthor = articlesForAuthor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByModerator")
    public Set<Article> getArticlesForModerator() {
        return this.articlesForModerator;
    }
    
    public void setArticlesForModerator(Set<Article> articlesForModerator) {
        this.articlesForModerator = articlesForModerator;
    }




}


